# This is a basic workflow to help you get started with Actions

name: Package Publication

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the tags
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"

      - name: "Automated Version Bump"
        id: bump_version
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Bump new tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          custom_tag: ${{ steps.bump_version.outputs.newTag }}
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.newTag }}
          release_name: Release ${{ steps.bump_version.outputs.newTag }}
          body: ${{ steps.tag_version.outputs.changelog }}
